[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
evm_version = 'shanghai'
auto_detect_remappings = true
eth-rpc-url = "https://ethereum-sepolia.blockpi.network/v1/rpc/public"
libraries = []
cache = true
cache_path = 'cache'
broadcast = 'broadcast'
gas_reports = ['*']
gas_reports_ignore = []
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
