[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.4"
evm_version = 'paris'
auto_detect_remappings = true
eth-rpc-url = "https://binance.llamarpc.com"
libraries = []
cache = false
cache_path = 'cache'
broadcast = 'broadcast'
gas_reports = ['*']
gas_reports_ignore = []
auto_detect_solc = true
offline = false
optimizer = false
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
